### ISSUE TITLE
Framework question

### ISSUE THREAD

**Issue by reteps** [CTFd/core-beta#49]
- Is there a place where the selection of alpine over vue was discussed?

After running [UIUCTF 2023](https://2023.uiuc.tf), I felt that alpine was insufficient for our needs, and would have greatly preferred a Vue base. I am considering doing a full rewrite of core-beta in Vue, but would be happy to talk more about it with you first.

**Comment by ColdHeat** [comment]
I'm not sure it was publicly discussed but there's a number of issues in the CTFd repo that discuss Vue and this is the first issue talking about it since core-beta was open sourced. 

https://github.com/CTFd/CTFd/issues/1139
https://github.com/CTFd/CTFd/issues/1742
https://github.com/CTFd/CTFd/issues/730

From internal testing Vue just wasn't as nice as Alpine for situations where the user did not have a build system in place and was just working with raw HTML. 

Currently the perspective is that CTFd should use Vue for components where a user is unlikely to need to modify it or add functionality. For example most Admin Panel components are implemented in Vue. However CTFd should use Alpine for areas where it is expected that the user may need to add or override functionality without having to add a new JS entrypoint or mess with the build system. 

I think this principle works best and even the Admin Panel will eventually have Alpine as well as Vue.

Likely if there was no plugin system or Pages system where users will write raw HTML, Vue would probably have been preferred. That being said, nothing really stops you from using Vue. I also just realized that Vue is actually still a dependency in package.json. Ultimately as long as you use CTFd.js you should be completely fine with whatever front end framework you choose. 

I do feel like this is a bit a matter of preference since I have benefited from core-beta being Alpine-based versus Vue-based since I feel like Alpine made some things easier for me than Vue would have. But I do recognize that if you are doing something complex, Vue is probably a better choice. 

I'm not against having Vue components as long as they consider whether or not the user is expected to customize/modify them. I really view Alpine more as a replacement for jQuery than I do a replacement for Vue.

**Comment by ColdHeat** [comment]
I also found this issue https://github.com/CTFd/CTFd/issues/2047

**Comment by reteps** [comment]
Thanks for the detailed response. I will continue as planned, with making a vue-based theme. If this was completed, would you consider merging this upstream as an alternative to core-beta?

**Comment by ColdHeat** [comment]
I would consider it if asked but I am not sure if it would be merged into the CTFd repository. That would result in splitting development efforts. CTFd is structured such you can maintain it seperately.

**Comment by ColdHeat** [comment]
While skimming our documentation I found this which basically reiterated what I said earlier: https://docs.ctfd.io/docs/themes/alpine-js

We may consider Vue in the future. I do view CTFd.js as the actual theme interface and core-beta simply a prepackaged theme that shows how everything is used so there's really not much overall preference in front end framework.
